const clientFolder = [
  "client",
  "client/c",
  "client/c/lib",
  "client/components",
  "client/components/collection",
  "client/components/contentManagement",
  "client/components/contentManagement/contentTypes",
  "client/components/contentManagement/mediaManagementPanel",
  "client/components/global",
  "client/components/settings",
  "client/components/settings/users",
  "client/components/ui",
  "client/layout",
  "client/pages",
  "client/pages/collections",
  "client/pages/collections/[collectionName]",
  "client/pages/content-management",
  "client/pages/content-management/[collectionName]",
  "client/pages/settings",
  "client/pages/settings/roles",
  "client/pages/settings/users",
  "client/public",
  "public",
  "public/files",
  "public/images",
  "src",
  "src/custom",
  "src/custom/controllers",
  "src/custom/routes",
  "src/schemas"
];

export default clientFolder;